INSERT INTO subcategoria (id, nombre, categoria_id) VALUES
(1, 'Martillos', 1),
(2, 'Destornilladores', 1),
(3, 'Llaves', 1),
(4, 'Herramientas Eléctricas', 1),
(5, 'Taladros', 1),
(6, 'Sierras', 1),
(7, 'Lijadoras', 1),
(8, 'Materiales de Construcción', 1),
(9, 'Cemento', 2),
(10, 'Arena', 2),
(11, 'Ladrillos', 2),
(12, 'Acabados', 2),
(13, 'Pinturas', 2),
(14, 'Barnices', 2),
(15, 'Cerámicos', 2),
(16, 'Cascos', 3),
(17, 'Guantes', 3),
(18, 'Lentes de Seguridad', 3),
(19, 'Accesorios Varios', 3);